repositories:
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/
- name: 1password
  url: https://1password.github.io/connect-helm-charts/
- name: metallb
  url: https://metallb.github.io/metallb
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: keel
  url: https://charts.keel.sh
- name: tailscale
  url: https://pkgs.tailscale.com/helmcharts
- name: jetstack
  url: https://charts.jetstack.io
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/
- name: democratic-csi
  url: https://democratic-csi.github.io/charts/
- name: openebs
  url: https://openebs.github.io/openebs
- name: nvdp
  url: https://nvidia.github.io/k8s-device-plugin
- name: nfd
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
- name: intel
  url: https://intel.github.io/helm-charts/
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: stakater
  url: https://stakater.github.io/stakater-charts
- name: longhorn
  url: https://charts.longhorn.io
- name: emqx
  url: https://repos.emqx.io/charts
- name: vm
  url: https://victoriametrics.github.io/helm-charts/

releases:

# 1Password Secrets
- name: connect
  namespace: onepassword
  chart: 1password/connect
  set:
    - name: operator.create
      value: true
    - name: operator.token.value
      file: .secrets/1password-token
    - name: connect.credentials
      file: .secrets/1password-credentials.json

# Tailscale stuff
- name: tailscale-operator
  namespace: tailscale
  chart: tailscale/tailscale-operator
  setString:
    - name: oauth.clientId
      value: "op://fmycvdzmeyvbndk7s7pjyrebtq/e3wesi6ceugqjhpuctsa3qvrcu/username"
    - name: oauth.clientSecret
      value: "op://fmycvdzmeyvbndk7s7pjyrebtq/e3wesi6ceugqjhpuctsa3qvrcu/credential"
    - name: apiServerProxyConfig.mode
      value: "true"

# Load balancer
- name: metallb
  namespace: metallb-system
  chart: metallb/metallb
  values:
    - metallb/values.yaml
  hooks:
    - events: ["postsync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "metallb/pool.yaml"]
    - events: ["postuninstall"]
      showlogs: true
      command: "kubectl"
      args: ["delete", "-f", "metallb/pool.yaml"]

# K8s dashboard
- name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  hooks:
    - events: ["postsync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "dashboard/resources.yaml"]
    - events: ["postuninstall"]
      showlogs: true
      command: "kubectl"
      args: ["delete", "-f", "dashboard/resources.yaml"]

# Private keen.land ingress
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx

# Private keen.land ingress
- name: ingress-nginx-public-fly
  namespace: ingress-nginx-public-fly
  chart: ingress-nginx/ingress-nginx 
  values:
    - ingress-nginx-public-fly/values.yaml

# Public ingress (runs at vultr)
- name: ingress-nginx-public
  namespace: ingress-nginx-public
  chart: ingress-nginx/ingress-nginx
  values:
    - ingress-nginx-public/values.yaml

# Auto-update pods when containers update
- name: keel
  namespace: kube-system
  chart: keel/keel

# Maintain certificates for ingress
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  set:
    - name: crds.enabled
      value: true
    - name: dns01RecursiveNameserversOnly
      value: true
  setString:
    - name: dns01RecursiveNameservers
      value: "8.8.8.8:53,1.1.1.1:53"

# Set IPs for ingress in route53
- name: external-dns
  namespace: external-dns
  chart: external-dns/external-dns

# Storage on NAS (morbo)
- name: zfs-nfs
  namespace: democratic-csi
  chart: democratic-csi/democratic-csi
  values:
    - zfs-nfs/values.yaml
  setString:
    - name: driver.config.httpConnection.password
      value: "op://fmycvdzmeyvbndk7s7pjyrebtq/kgcd45ae35qjybkqluukhv4z7y/ADMIN_PASSWORD"

# Local storage
- name: openebs
  namespace: openebs
  chart: openebs/openebs
  values:
    - openebs/values.yaml

# Set node labels based on hardware etc
- name: nfd
  namespace: node-feature-discovery
  chart: nfd/node-feature-discovery
  values:
    - node-feature-discovery/values.yaml

# Set node labels for nvidia GPUs
- name: nvidia-device-plugin
  chart: nvdp/nvidia-device-plugin
  namespace: nvidia
  set:
    - name: gfd.enabled
      value: true
    - name: nfd.enabled
      value: false
    - name: allowDefaultNamespace
      value: true
    - name: runtimeClassName
      value: "nvidia"
  hooks:
    - events: ["preapply"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "nvidia-device-plugin/resources.yaml"]

# Set labels for intel devices
- name: dp-operator
  namespace: inteldeviceplugins-system
  chart: intel/intel-device-plugins-operator

# Set labels for intel GPUs
- name: gpu
  namespace: inteldeviceplugins-system
  chart: intel/intel-device-plugins-gpu
  set:
    - name: nodeFeaturesRule
      value: true

# Postgresql databases
- name: cnpg
  namespace: cnpg-system
  chart: cnpg/cloudnative-pg

# Reload deployments when configmaps or secrets change
- name: reloader
  namespace: reloader
  chart: stakater/reloader

# replicated local storage
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  values:
    - longhorn/values.yaml
  # hooks:
  #   - events: ["postsync"]
  #     showlogs: true
  #     command: "kubectl"
  #     args: ["apply", "-f", "longhorn/resources.yaml"]

# replicated mqtt server
- name: emqx-operator
  namespace: emqx-operator-system
  chart: emqx/emqx-operator

# centralized logging
- name: vls
  chart: vm/victoria-logs-single
  namespace: vm-system
  values:
    - victorialogs/values.yaml

# metrics collection
- name: vm
  chart: vm/victoria-metrics-cluster
  namespace: vm-system
  values:
    - victoriametrics/values.yaml
