kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zfs-nfs-pvc
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-zfs-nfs
spec:
  volumes:
  - name: zfs-nfs-storage
    persistentVolumeClaim:
      claimName: zfs-nfs-pvc
  containers:
  - name: hello-container
    image: busybox
    command:
       - sh
       - -c
       - 'while true; do echo "`date` [`hostname`] Hello from democratic-csi." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
    volumeMounts:
    - mountPath: /mnt/store
      name: zfs-nfs-storage
