apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:pod-bindings
  labels:
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
rules:
  - apiGroups: [""]
    resources: ["pods/binding"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:pod-bindings-update
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
  - apiGroups: [""]
    resources: ["pods/binding", "pods", "nodes", "services"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ser2net-service-per-pod
spec:
  rules:
  - name: generic-pod-labels
    match:
      any:
      - resources:
          kinds:
          - Pod/binding
    mutate:
      mutateExistingOnPolicyUpdate: true
      targets:
        - apiVersion: v1
          kind: Pod
          name: "{{ request.object.metadata.name }}"
          namespace: "{{ request.object.metadata.namespace }}"
      patchStrategicMerge:
        metadata:
          labels:
            podName: "{{ request.object.metadata.name }}"
            nodeName: "{{ request.object.target.name }}"
  - name: service-per-pod
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchExpressions:
              - {key: app, operator: In, values: ['ser2net']}
              - {key: nodeName, operator: Exists}
          operations:
            - UPDATE
    context:
      - name: node
        variable:
          jmesPath: request.object.labels.nodeName
          default: ''
    generate:
      synchronize: true
      apiVersion: v1
      kind: Service
      name: "ser2net-{{ node }}"
      namespace: "iot-system"
      data:
        spec:
          type: ClusterIP
          clusterIP: None
          selector:
            app: ser2net
            podName: "{{ request.object.metadata.name }}"
          ports:
            - protocol: TCP
              port: 6636
              targetPort: 6636
              name: generator
            - protocol: TCP
              port: 6637
              targetPort: 6637
              name: waterfurnace
            - protocol: TCP
              port: 6638
              targetPort: 6638
              name: zwave
            - protocol: TCP
              port: 6639
              targetPort: 6639
              name: zigbee
