---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fly-ingress-wireguard-configs
  namespace: ingress-nginx-public-fly
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/esk22et4sbc3fubdv4qr3ybbxu"
