apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkdn
  labels:
    app: pkdn
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5m"
    keel.sh/approvals: "0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pkdn
  template:
    metadata:
      labels:
        app: pkdn
    spec:
      containers:
        - name: pkdn
          image: ghcr.io/peterkeen/site:nightly
      imagePullSecrets:
        - name: ghcr.io
---
apiVersion: v1
kind: Service
metadata:
  name: pkdn
spec:
  selector:
    app: pkdn
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pkdn-public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx-public
  tls:
    - hosts:
        - www.petekeen.net
        - petekeen.net
      secretName: public3-pkdn-ingress-cert
  rules:
    - host: www.petekeen.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pkdn
                port:
                  number: 8000
