---
clusterName: omicron
talosVersion: 1.9.5
kubernetesVersion: 1.32.3
endpoint: https://10.73.95.69:6443
domain: omicron.keen.land
patches:
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/openebs
          type: bind
          source: /var/openebs
          options:
            - bind
            - rshared
            - rw
  - |-
    machine:
      network:
        kubespan:
          enabled: true
          advertiseKubernetesNetworks: true
      kubelet:
        extraArgs:
          rotate-server-certificates: true

  - |-
    cluster:
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service: {}

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:reader
            allowedKubernetesNamespaces:
              - kube-system
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent

nodes:
  - hostname: hypnotoad-control
    ipAddress: 10.73.95.69
    installDisk: /dev/sda
    controlPlane: true
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"

  - hostname: crushinator-control
    ipAddress: 10.73.95.75
    installDisk: /dev/sda
    controlPlane: true
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"    

  - hostname: lrrr-control
    ipAddress: 10.73.95.209
    installDisk: /dev/sda
    controlPlane: true
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"    

  - hostname: hypnotoad-worker
    ipAddress: 10.73.95.207
    installDisk: /dev/sda
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent

  - hostname: nibbler-worker
    ipAddress: 10.73.95.205
    installDisk: /dev/sda
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
    kernelModules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset

    patches:
      - |-
        machine:
          sysctls:
            net.core.bpf_jit_harden: 1

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/i915

  - hostname: cloud-ord-1
    ipAddress: 144.202.49.178
    installDisk: /dev/vda
    nodeLabels:
      topology.kubernetes.io/zone: "ord-v"    
      cloud: true
