---
clusterName: omicron
talosVersion: 1.9.5
kubernetesVersion: 1.32.3
endpoint: https://10.73.95.75:6443
domain: omicron.keen.land
patches:
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/openebs
          type: bind
          source: /var/openebs
          options:
            - bind
            - rshared
            - rw
        - destination: /var/lib/longhorn
          type: bind
          source: /var/lib/longhorn
          options:
            - bind
            - rshared
            - rw
        - destination: /var/mnt/storage
          type: bind
          source: /var/mnt/storage
          options:
            - bind
            - rshared
            - rw          
  - |-
    machine:
      network:
        kubespan:
          enabled: true
          advertiseKubernetesNetworks: true
      kubelet:
        extraArgs:
          rotate-server-certificates: true

  - |-
    cluster:
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service: {}

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:reader
            allowedKubernetesNamespaces:
              - kube-system
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

nodes:
  - hostname: crushinator-control
    ipAddress: 10.73.95.75
    installDisk: /dev/sda
    controlPlane: true
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"

  - hostname: lrrr-control
    ipAddress: 10.73.95.209
    installDisk: /dev/sda
    controlPlane: true
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"

  # - hostname: morbo-control
  #   ipAddress: 10.73.95.228
  #   installDisk: /dev/vda
  #   controlPlane: true
  #   nodeLabels:
  #     topology.kubernetes.io/zone: "home-1"

  # - hostname: hypnotoad-worker
  #   ipAddress: 10.73.95.207
  #   installDisk: /dev/sda
  #   nodeLabels:
  #     metallb: true
  #     topology.kubernetes.io/zone: "home-1"
  #   schematic:
  #     customization:
  #       systemExtensions:
  #         officialExtensions:
  #           - siderolabs/qemu-guest-agent
  #           - siderolabs/iscsi-tools
  #           - siderolabs/util-linux-tools

  - hostname: nibbler
    ipAddress: 10.73.95.176
    installDisk: /dev/sda
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
    kernelModules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: i915

    patches:
      - |-
        machine:
          sysctls:
            net.core.bpf_jit_harden: 1

      - |-
        - op: add
          path: /machine/disks
          value:
            - device: /dev/nvme0n1
              partitions:
                - mountpoint: /var/mnt/storage

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

  - hostname: hypnotoad
    ipAddress: 10.73.95.234
    installDisk: /dev/sdb
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
    kernelModules:
      - name: i915
    controlPlane: true        

    patches:
      - |-
        machine:
          sysctls:
            net.core.bpf_jit_harden: 1
      - |-
        cluster:
          allowSchedulingOnControlPlanes: true

      - |-
        - op: add
          path: /machine/disks
          value:
            - device: /dev/nvme0n1
              partitions:
                - mountpoint: /var/mnt/storage

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools            

  - hostname: cloud-ord-1
    ipAddress: 144.202.49.178
    installDisk: /dev/vda
    nodeLabels:
      topology.kubernetes.io/zone: "ord-v"
      cloud: true
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
