---
clusterName: omicron
talosVersion: 1.10.4
kubernetesVersion: 1.33.2
endpoint: https://10.73.95.209:6443
domain: omicron.keen.land
patches:
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/openebs
          type: bind
          source: /var/openebs
          options:
            - bind
            - rshared
            - rw
        - destination: /var/lib/longhorn
          type: bind
          source: /var/lib/longhorn
          options:
            - bind
            - rshared
            - rw
        - destination: /var/mnt/storage
          type: bind
          source: /var/mnt/storage
          options:
            - bind
            - rshared
            - rw
  - |-
    machine:
      network:
        kubespan:
          enabled: true
          advertiseKubernetesNetworks: true
      kubelet:
        extraArgs:
          rotate-server-certificates: true
      features:
        hostDNS:
          resolveMemberNames: true

  - |-
    cluster:
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service: {}

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:reader
              - os:etcd:backup
            allowedKubernetesNamespaces:
              - kube-system
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

nodes:
  - hostname: lrrr-control
    ipAddress: 10.73.95.209
    installDisk: /dev/sda
    controlPlane: true
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"
    networkInterfaces:
      - interface: eth0
        dhcp: true

  - hostname: crushinator
    ipAddress: 10.73.95.176
    installDisk: /dev/sda
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
      keen.land/rfZone: "office"
    controlPlane: false

    patches:
      - |-
        machine:
          sysctls:
            net.core.bpf_jit_harden: 1
      - |-
        cluster:
          allowSchedulingOnControlPlanes: true
      - |-
        - op: add
          path: /machine/disks
          value:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/storage
            - device: /dev/sdc
              partitions:
                - mountpoint: /var/mnt/nvme_storage

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
    networkInterfaces:
      - interface: br0
        dhcp: true
        bridge:
          stp:
            enabled: true
          interfaces:
              - ens18

  - hostname: nibbler
    ipAddress: 10.73.95.97
    installDisk: /dev/nvme0
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
      keen.land/rfZone: "house"
    kernelModules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: i915
    patches:
      - |-
        machine:
          install:
            extraKernelArgs:
              - pcie_aspm=off
      - |-
        machine:
          sysctls:
            net.core.bpf_jit_harden: 1

    userVolumes:
      - name: storage
        provisioning:
          diskSelector:
            match: disk.transport == "nvme" 
          minSize: 1.8TiB

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

    networkInterfaces:
      - interface: br0
        dhcp: true
        bridge:
          stp:
            enabled: true
          interfaces:
            - eno1

  - hostname: hypnotoad
    ipAddress: 10.73.95.234
    installDisk: /dev/sdb
    nodeLabels:
      metallb: true
      topology.kubernetes.io/zone: "home-1"
      keen.land/rfZone: "house"
    kernelModules:
      - name: i915
    controlPlane: false

    patches:
      - |-
        machine:
          sysctls:
            net.core.bpf_jit_harden: 1
      - |-
        cluster:
          allowSchedulingOnControlPlanes: true

      - |-
        - op: add
          path: /machine/disks
          value:
            - device: /dev/nvme0n1
              partitions:
                - mountpoint: /var/mnt/storage

    networkInterfaces:
      - interface: br0
        dhcp: true
        bridge:
          stp:
            enabled: true
          interfaces:
            - eno1
            - enp1s0

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

  - hostname: cloud-ord-1
    ipAddress: 144.202.49.178
    installDisk: /dev/vda
    nodeLabels:
      topology.kubernetes.io/zone: "ord-v"
      cloud: true
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

  - hostname: wyse-3040-9c0d
    ipAddress: 10.73.95.159
    installDisk: /dev/sda
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"
      location: "mediacloset"
      keen.land/rfZone: "house"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

    networkInterfaces:
      - interface: br0
        dhcp: true
        bridge:
          stp:
            enabled: true
          interfaces:
            - enp1s0

  - hostname: wyse-3040-9835
    ipAddress: 10.73.95.223
    installDisk: /dev/sdb
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"
      location: "office"
      keen.land/rfZone: "office"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

    networkInterfaces:
      - interface: br0
        dhcp: true
        bridge:
          stp:
            enabled: true
          interfaces:
            - enp1s0

  # - hostname: wyse-3040-9855
  #   ipAddress: 10.73.95.65
  #   installDisk: /dev/sda
  #   nodeLabels:
  #     topology.kubernetes.io/zone: "home-1"
  #     location: "garage"
  #     keen.land/rfZone: "garage"
  #   schematic:
  #     customization:
  #       systemExtensions:
  #         officialExtensions:
  #           - siderolabs/iscsi-tools
  #           - siderolabs/util-linux-tools

    # networkInterfaces:
    #   - interface: br0
    #     dhcp: true
    #     bridge:
    #       stp:
    #         enabled: true
    #       interfaces:
    #         - enp1s0

  - hostname: shed
    ipAddress: 10.73.95.225
    installDisk: /dev/sdb
    nodeLabels:
      topology.kubernetes.io/zone: "home-1"
      location: "shed"
      keen.land/rfZone: "shed"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

    networkInterfaces:
      - interface: br0
        dhcp: true
        bridge:
          stp:
            enabled: true
          interfaces:
            - enp1s0
