global:
  cluster:
    dnsDomain: omicron.keen.land.

server:
  persistentVolume:
    enabled: true
    storageClassName: longhorn
  nodeSelector:
    topology.kubernetes.io/zone: home-1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - name: metrics.keen.land
        path:
          - /
        port: http
    tls:
      - hosts:
          - metrics.keen.land
        secretName: keenland-victoriametrics-ingress-cert
